apiVersion: v1
kind: Pod
metadata:
  name: nccl-server-1
spec:
  hostNetwork: false
  runtimeClassName: nvidia
  volumes:
          - name: dshm
            emptyDir:
              medium: Memory
  containers:
  - name: app
    image: nvcr.io/nvidia/cuda:12.2.2-devel-ubuntu20.04
    securityContext:
      allowPrivilegeEscalation: true
    volumeMounts:
            - mountPath: /dev/shm
              name: dshm
    command: ["/bin/bash"]
    args: ["-c", "sleep 360000"]
    resources:
      limits:
        nvidia.com/gpu: 8
        nvidia.com/hostdev: 8
        memory: 8000Mi
      requests:
        nvidia.com/gpu: 8
        nvidia.com/hostdev: 8
        memory: 8000Mi
